### ISSUE TITLE
Screenshot is taken after browser is already closed

### ISSUE THREAD

**Issue by nazarmartin** [allure-framework/allure-csharp-commons#17]
Hello, 

Could you please take a look at the following issue. Allure takes screenshot in incorrect time (e.g. when browser is already closed). This is just an example of my test (nUnit)

``` C#
ChromeDriver driver = new ChromeDriver();
public void SampleTest()
        {           
            driver.Manage().Window.Maximize();
            driver.Navigate().GoToUrl("http://localhost/Basic.html");
            Assert.Fail();
        }

[TearDown]
        public void TearDown()
        {
            driver.Close();
            driver.Quit();
        }
```

Could you please advise if this can be fixed or there is any workaround for this?

**Comment by ilya-murzinov** [comment]
Hi, @nazarmartin, I can't see where you take screenshot in your snippet.

**Comment by nazarmartin** [comment]
Hi, @ilya-murzinov , thank you for quick response :+1: 
I am setting take screen in Allure config file:
```
<take-screenshots-after-failed-tests>true</take-screenshots-after-failed-tests>
```

**Comment by ilya-murzinov** [comment]
@nazarmartin, ok, I see..
I'll take a look.

**Comment by ilya-murzinov** [comment]
@nazarmartin, I believe that the problem in ```[TearDown]``` attribute. You should use ```[TestFixtureTearDown]``` instead. Is it possible?

**Comment by nazarmartin** [comment]
@ilya-murzinov , I think that will not work for me. In my tests I am using SpecFlow and it's Binding Attribute. I guess analog for [TestFixtureTearDown] is [AfterScenario] in SpecFlow. I tried to put my dispose methods there but no luck.

**Comment by ilya-murzinov** [comment]
@nazarmartin, thanks for the info. Actually, you are not the first one experiencing this problem.
So I think I'm gonna remove **take-screenshots-after-failed-tests** parameter at all.

It's not the adapter's responsibility after all.

**Comment by nazarmartin** [comment]
@ilya-murzinov , did you have a chance to think regarding attaching WebDriver reports to Allure reports? Maybe some thoughts where I should probable dig to implement this?

**Comment by ilya-murzinov** [comment]
@nazarmartin, I don't know, what the WebDriver report is.

**Comment by nazarmartin** [comment]
@ilya-murzinov , sorry I mean WebDriver screenshots. So the idea is to make screenshot in my tests. The question is how to attach them to Allure report?

**Comment by ilya-murzinov** [comment]
@nazarmartin, actually, this is the big question.
I have #3 issue for this and even a #15 pull-request, but I still don't have time to dig into it..

**Comment by ilya-murzinov** [comment]
@nazarmartin, although, NUnit 3 will be released soon and this issue might become irrelevant for it.

**Comment by nazarmartin** [comment]
@ilya-murzinov , could you please advise what exact change in Nunit you are reference to?

**Comment by ilya-murzinov** [comment]
@nazarmartin, NUnit will support modular architecture which will make easy to do a lot of customization. I don't know details, I'll wait until at least beta version released.

**Comment by sergmal** [comment]
Could someone explain please how to make a screenshot without using "take-screenshots-after-failed-tests" parameter? Because for me it also taking screenshot when browser closed.

Something like this?

```
[TearDown]
        public void TearDown()
        {

	    _lifecycle = Allure.DefaultLifecycle;
            _lifecycle.Fire(new MakeAttachmentEvent(AllureResultsUtils.TakeScreenShot(),
                "Screenshot",
                "image/png"));
            driver.Close();
            driver.Quit();
        }
```

**Comment by baev** [comment]
this repo is deprecated, please use https://github.com/allure-framework/allure-csharp instead
