### ISSUE TITLE
Support for [Issue], [Ignore] attributes, and steps

### ISSUE THREAD

**Issue by lisss** [allure-framework/allure-csharp-commons#20]
Hi,
Have a few questions regarding the NUnit adapter and .NET support in general.
1) I've seen you've implemented the `@Issue` annotation support for Java frameworks - is there any intention to do the same for NUnit adapter? 
2) Is there any intention to add Step attribute to NUnit adapter? (there is a support of test steps in AllureCSharpCommons tho... and there is already open issue on that - https://github.com/allure-framework/allure-csharp-commons/issues/3)
3) Is there any intention to allow customization/enhancement of test state? For now, I find it quite unusable to not have the _'ignored'_ state for the NUnit tests being ignored - they now are marked as _'pending'_ which is confusing

Just wondering if you pay any attention to the .NET support atm and is there a reason to wait for updates from your side or it's better to fork the projects :)

**Comment by vania-pooh** [comment]
@lisss currently we have no real maintainer for .NET stuff because we're not working with Microsoft stack. So if someone could contribute - welcome to our community.

**Comment by ilya-murzinov** [comment]
Yeah, I don't have time to contribute anymore, but ping me if you need any help with this (questions etc).

**Comment by lisss** [comment]
@vania-pooh, @ilya-murzinov, thanks guys for the quick response

**Comment by baev** [comment]
this repo is deprecated, please use https://github.com/allure-framework/allure-csharp instead
