### ISSUE TITLE
Plans to migrate to dotnet Core (Port in CoreCLR)

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure-csharp-commons#22]
Hi,
We are migrating our projects to .net core.
Do you have any plans to migrate it to .net core?

**Comment by Bakanych** [comment]
I'm thinking to create support for Allure2. Which version are you using now?

**Comment by arpit-nagar** [comment]
Thanks for your response.

We are using Allure1 right now for .net framework 461. We use xUnit as a testing library and execute test via vstest.console.exe on windows platform. And then convert trx to Allure files via tool [MsTest](https://github.com/allure-framework/allure-mstest).

We are in process of migrating all of the projects to .net core which runs on Linux.
We want to migrate to Allure2 but it does not have support of xUnit as of now. 
If you are planning to migrate it to Allure2, please create this in .net core so that it will be available for all .net versions. and can easily be available for xUnit plugin of .net core.
If you need any help please let me know.

**Comment by arpit-nagar** [comment]
Any progress on supporting it to Allure2?

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by Bakanych** [comment]
@arpit-nagar hi,
The first migration approach is done, please check [Allure 2 csharp-commons](https://github.com/allure-framework/allure-csharp/tree/master/allure-csharp-commons-v2).
I'm not sure there will be any updates of the 1st version of allure csharp commons.
Please consider migration to Allure 2.

Good luck!

**Comment by arpit-nagar** [comment]
Awesome 👍

**Comment by Bakanych** [comment]
@arpit-nagar  Thanks :)
But keep in mind, .net test adapters haven't been ported yet...
