### ISSUE TITLE
How to use Allure Attributes with SpecFlow?

### ISSUE THREAD

**Issue by koreyba** [allure-framework/allure-csharp-commons#23]
There are a few attributes that Allure allows to use: https://github.com/allure-framework/allure-csharp-commons/tree/master/AllureCSharpCommons/Attributes	

**They are:**
- AllureDescriptionAttribute
- AllureFeaturesAttribute
- AllureSeverityAttribute
- AllureStoriesAttribute
- AllureTitleAttribute

Is it possible to use them with SpecFlow?

I know that AllureSeverityAttribute can be used by adding a tag to SpecFlow Scenario like @blocker, but it also requires special allureConfig like:

```
"specflow": {
    "stepArguments": {
      "convertToParameters": "true",
      "paramNameRegex": "",
      "paramValueRegex": ""
    },
    "grouping": {
      "suites": {
        "parentSuite": "^parentSuite:?(.+)",
        "suite": "^suite:?(.+)",
        "subSuite": "^subSuite:?(.+)"
      },
      "behaviors": {
        "epic": "^epic:?(.+)",
        "story": "^story:(.+)"
      }
    },
    "labels": {
      "owner": "^author:?(.+)",
      "severity": "^(normal|blocker|critical|minor|trivial)"
    },
    "links": {
      "tms": "^story:(.+)",
      "issue": "^issue:(.+)",
      "link": "^link:(.+)"
    }
```

But what about all the other attributes?

**Comment by Bakanych** [comment]
hi @koreyba , https://github.com/allure-framework/allure-csharp-commons is now deprecated and not supported anymore.
Please follow https://github.com/allure-framework/allure-csharp repository.

**Comment by koreyba** [comment]
> hi @koreyba , https://github.com/allure-framework/allure-csharp-commons is now deprecated and not supported anymore.
> Please follow https://github.com/allure-framework/allure-csharp repository.

Thanks. Does it mean that listed attributes are not supported anymore? I haven't found them in the new repository.
