### ISSUE TITLE
Add Step, Attachment and Parameter attributes handling

### ISSUE THREAD

**Issue by ilya-murzinov** [allure-framework/allure-csharp-commons#3]
Using, for example, [Mono Cecil](https://github.com/jbevain/cecil) to intercept method calls.

**Comment by sergmal** [comment]
Really looking for Step feature..

**Comment by sergmal** [comment]
Hi,

From here: https://github.com/allure-framework/allure-csharp-commons/wiki/Events
I see that Step is supported in C#?

How to use it?
Thanks

**Comment by baev** [comment]
this repo is deprecated, please use https://github.com/allure-framework/allure-csharp instead
